trigger:
- master

variables:
  buildConfiguration: 'Release'

steps:
  command: 'build'
  arguments: --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  